services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hyojo
      POSTGRES_USER: hyojo
      POSTGRES_PASSWORD: hyojo
    ports:
      - "5432:5432"
    volumes:
      - hyojo-postgres:/var/lib/postgresql/data

volumes:
  hyojo-postgres:
