"use client";

import { useState } from "react";

export default function ProductPreview() {
  const [text, setText] = useState("");
  const [notice, setNotice] = useState("");
  const [huddle, setHuddle] = useState(false);
  const [done, setDone] = useState(false);
  const [reminder, setReminder] = useState(false);
  function speak() { if (!text.trim()) return; setNotice("承知しました。判断に必要な論点を1枚にまとめました。"); setText(""); }
  return <main style={s.page}><section style={s.phone}><header style={s.header}><span>7月22日 水 · 朝</span><b>HYOJO</b></header><div style={s.content}><p style={s.greeting}>おはよう、Toru。</p><h1 style={s.title}>今、決めると前に進むことがひとつあります。</h1>{notice && <p style={s.notice}>{notice}</p>}<article style={{...s.card,background:"#F4FAF6",borderColor:"#D7E8DD"}}><small style={s.label}>AI が今の判断用にまとめました</small><strong style={s.cardTitle}>48時間案を、ここで決めますか？</strong><p style={s.copy}>Sarahも合意済みです。返金ポリシーを声で確定できます。</p><button onClick={() => setHuddle(true)} style={s.primary}>判断を聞く</button></article>{huddle && <article style={s.card}><small style={s.label}>HUDDLE</small><strong style={s.cardTitle}>Sarahと10分ハドル</strong><p style={s.copy}>録画・文字起こしは参加前に明示し、同意後に開始します。</p><button onClick={() => { setHuddle(false); setNotice("Huddleを開始しました。記録は参加者に表示されます。"); }} style={s.primary}>同意して参加する</button></article>}<section style={s.list}><small style={s.listLabel}>いまやること</small>{!done ? <div style={s.row}><div><b>CSマニュアルを更新する</b><p>AI · 返金ポリシーを決める</p></div><div><button onClick={() => setDone(true)} style={s.textButton}>完了</button><button onClick={() => { setReminder(true); setNotice("1時間後にお知らせします。"); }} style={s.textButton}>{reminder ? "予約済" : "あとで"}</button></div></div> : <p style={s.done}>✓ CSマニュアルを更新する を完了しました</p>}</section></div><footer style={s.composer}><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && speak()} placeholder="話す（宛先は要らない）"/><button onClick={speak}>送る</button></footer></section><aside style={s.aside}><p>HYOJO / モバイルWebレビュー</p><h2>ユーザーが触る画面です。</h2><p>左のスマホ画面で、判断 → Huddle同意 → TODO完了／リマインドまでを実際に操作できます。ネイティブ通話・通知は実機ビルドへ移行後に有効化します。</p></aside></main>;
}

const s: Record<string, React.CSSProperties> = { page:{minHeight:"100vh",display:"flex",gap:56,alignItems:"center",justifyContent:"center",padding:32,background:"#E9E9E4"},phone:{width:390,minHeight:780,background:"#fff",borderRadius:32,overflow:"hidden",boxShadow:"0 20px 60px #0003",position:"relative",display:"flex",flexDirection:"column"},header:{height:56,padding:"0 20px",borderBottom:"1px solid #E2E2DD",display:"flex",alignItems:"center",justifyContent:"space-between",fontSize:11,color:"#666"},content:{padding:20,display:"grid",gap:16,overflow:"auto"},greeting:{fontSize:16,margin:0},title:{fontSize:21,lineHeight:1.5,fontWeight:500,margin:0},notice:{fontSize:12,color:"#0F6E56",margin:0},card:{border:"1px solid #C8C8C4",borderRadius:12,padding:16,display:"grid",gap:9},label:{fontSize:10,color:"#0F6E56",fontWeight:700},cardTitle:{fontSize:15},copy:{fontSize:12,lineHeight:1.6,color:"#555",margin:0},primary:{background:"#1A1A1A",color:"#fff",border:0,borderRadius:7,padding:"11px 14px",justifySelf:"start",cursor:"pointer"},list:{borderTop:"1px solid #E2E2DD",paddingTop:12,display:"grid",gap:8},listLabel:{fontSize:11,color:"#666",fontWeight:700},row:{padding:"10px 0",display:"flex",justifyContent:"space-between",gap:8,borderBottom:"1px solid #F0F0EC",fontSize:13},textButton:{fontSize:10,border:"1px solid #C8C8C4",borderRadius:6,background:"#fff",padding:"6px",marginLeft:4,cursor:"pointer"},done:{fontSize:12,color:"#0F6E56"},composer:{marginTop:"auto",padding:12,borderTop:"1px solid #E2E2DD",display:"flex",gap:8},aside:{maxWidth:320,color:"#41413D",lineHeight:1.6},asideP:{fontSize:14},headerB:{letterSpacing:1} };
