import { buildApp } from "./app.js";

const app = await buildApp();
const ready = await app.inject({ method: "GET", url: "/readyz" });
if (ready.statusCode !== 200 || ready.json().storage.persistent !== false) throw new Error("Development readiness failed");
const response = await app.inject({ method: "POST", url: "/v1/speak", headers: { "x-hyojo-actor": "toru" }, payload: { text: "Sarah と5分話したい" } });
if (response.statusCode !== 200) throw new Error(`Speak failed: ${response.statusCode}`);
const payload = response.json();
if (payload.narration?.surface?.kind !== "approval" || payload.auditEvents?.length !== 2) throw new Error("Unexpected Speak response");
const approval = await app.inject({ method: "POST", url: "/v1/approvals/refund-48h/approve", headers: { "x-hyojo-actor": "toru" } });
if (approval.statusCode !== 200 || approval.json().auditEvent.action !== "surface_approved") throw new Error("Approval audit failed");
const auditLog = await app.inject({ method: "GET", url: "/v1/audit-events", headers: { "x-hyojo-actor": "toru" } });
if (auditLog.statusCode !== 200 || !auditLog.json().events.some((event: { action: string }) => event.action === "surface_approved")) throw new Error("Admin audit log failed");
const expiringPolicy = await app.inject({ method: "PATCH", url: "/v1/spaces/product/recording-policy", headers: { "x-hyojo-actor": "toru" }, payload: { mode: "required", videoRetentionDays: 30, transcriptRetentionDays: 0, allowMemoryIndexing: true } });
if (expiringPolicy.statusCode !== 200) throw new Error("Retention policy setup failed");
const proposed = await app.inject({ method: "POST", url: "/v1/huddles", headers: { "x-hyojo-actor": "toru" }, payload: { title: "返金ポリシーを決める", participants: ["toru", "sarah"], spaceId: "product", recordingPolicy: "required" } });
if (proposed.statusCode !== 201 || proposed.json().huddle.status !== "proposed") throw new Error("Huddle proposal failed");
const huddleId = proposed.json().huddle.id;
const listed = await app.inject({ method: "GET", url: "/v1/huddles", headers: { "x-hyojo-actor": "toru" } });
if (listed.statusCode !== 200 || !listed.json().huddles.some((huddle: { id: string }) => huddle.id === huddleId)) throw new Error("Huddle list failed");
const cancellable = await app.inject({ method: "POST", url: "/v1/huddles", headers: { "x-hyojo-actor": "toru" }, payload: { title: "取り消すハドル", participants: ["toru"], spaceId: "product", recordingPolicy: "required" } });
const cancelled = await app.inject({ method: "POST", url: `/v1/huddles/${cancellable.json().huddle.id}/cancel`, headers: { "x-hyojo-actor": "toru" } });
if (cancelled.statusCode !== 204) throw new Error("Huddle cancellation failed");
const joined = await app.inject({ method: "POST", url: `/v1/huddles/${huddleId}/join`, headers: { "x-hyojo-actor": "toru" } });
if (joined.statusCode !== 200 || joined.json().huddle.recording.state !== "recording") throw new Error("Huddle recording start failed");
const unavailableToken = await app.inject({ method: "POST", url: `/v1/huddles/${huddleId}/token`, headers: { "x-hyojo-actor": "toru" } });
if (unavailableToken.statusCode !== 503 || !unavailableToken.json().error?.includes("LiveKit connection is not configured")) throw new Error("LiveKit configuration boundary failed");
const completed = await app.inject({ method: "POST", url: `/v1/huddles/${huddleId}/complete`, headers: { "x-hyojo-actor": "toru" } });
if (completed.statusCode !== 200 || completed.json().memory !== null || completed.json().huddle.recording.state !== "stopped") throw new Error("Huddle completion failed");
const transcript = await app.inject({ method: "POST", url: `/v1/huddles/${huddleId}/transcript`, headers: { "x-hyojo-actor": "toru" }, payload: { text: "Sarah agrees to a full refund within 48 hours from checkout.", language: "en", decisions: ["決済完了から48時間以内は全額返金"], todos: [{ owner: "AI", text: "CSマニュアルを更新する" }] } });
if (transcript.statusCode !== 200 || transcript.json().memory?.source !== "transcript" || transcript.json().memory?.decisions?.length !== 1 || transcript.json().huddle.transcript.state !== "received") throw new Error("Transcript memory ingestion failed");
const retention = await app.inject({ method: "POST", url: "/v1/admin/retention/run", headers: { "x-hyojo-actor": "toru" } });
if (retention.statusCode !== 200 || !retention.json().expiredHuddleIds.includes(huddleId)) throw new Error("Retention worker failed");
const expired = await app.inject({ method: "GET", url: `/v1/huddles/${huddleId}`, headers: { "x-hyojo-actor": "toru" } });
if (expired.json().memory !== null || expired.json().transcript.state !== "not_requested") throw new Error("Retention deletion failed");
const forbidden = await app.inject({ method: "GET", url: "/v1/spaces/product/recording-policy", headers: { "x-hyojo-actor": "unknown" } });
if (forbidden.statusCode !== 403) throw new Error("ACL boundary failed");
console.log("Speak smoke test passed");
await app.close();

const previousAuthMode = process.env.HYOJO_AUTH_MODE;
process.env.HYOJO_AUTH_MODE = "production";
const productionApp = await buildApp();
const productionReady = await productionApp.inject({ method: "GET", url: "/readyz" });
if (productionReady.statusCode !== 503) throw new Error("Production readiness boundary failed");
const spoofedHeader = await productionApp.inject({ method: "POST", url: "/v1/speak", headers: { "x-hyojo-actor": "toru" }, payload: { text: "This must not trust a header in production." } });
if (spoofedHeader.statusCode !== 401) throw new Error("Production header spoofing boundary failed");
await productionApp.close();
if (previousAuthMode === undefined) delete process.env.HYOJO_AUTH_MODE; else process.env.HYOJO_AUTH_MODE = previousAuthMode;
